docs/editor_integration.md

Ale supports it by default now

docs: remove instructions to manually use yamlfix with ale

---

src/yamlfix/services.py
tests/unit/test_services.py

fix: correct indentation of parent lists with comments

---

.github/workflows/tests.yml
docs/index.md
src/yamlfix/services.py
tests/unit/test_services.py

Correct comments in yaml files
closes #6

feat: manage comments

---

setup.py
src/yamlfix/__init__.py
src/yamlfix/services.py
tests/e2e/test_cli.py

chore: add typed data into the package.

---

.cruft.json
Makefile
docs/contributing.md
docs/index.md
docs/requirements.in
docs/requirements.txt
pyproject.toml
requirements-dev.txt
requirements.txt
setup.py
src/yamlfix/config.py
src/yamlfix/model/__init__.py
tests/conftest.py

chore: update cruft template

---

.cruft.json
.github/workflows/update.yml
Makefile

ci: hourly update the requirements

---

.github/workflows/update.yml
docs/requirements.txt
requirements-dev.txt
requirements.txt
setup.py

ci: update packages daily instead of hourly

---

.github/workflows/tests.yml
Makefile

ci: ignore tornado vulnerability

---

.pre-commit-config.yaml
docs/requirements.txt
requirements-dev.txt

ci: change black pre-commit version to master

---

.cruft.json
.github/workflows/build.yml
.github/workflows/install.yml
src/yamlfix/services.py

Otherwise the new package builder fails
feat: add a ci job to test that the program is installable

fix: install wheel in the build pipeline

---

.cruft.json
.github/workflows/update.yml
Makefile
docs/requirements.txt
pyproject.toml
requirements-dev.in
requirements-dev.txt
requirements.txt

ci: configure pytest to run tests in parallel
ci: update pip on the make update step

ci: remove the git hooks on the update workflow

---

.pre-commit-hooks.yaml

Fixing some problems with the pre-commit hook based on feedback from the pre-commit author at https://github.com/pre-commit/pre-commit.com/pull/640

Fix pre-commit hook

---

docs/examples/fix_code.py
docs/index.md
src/yamlfix/services.py
tests/unit/test_services.py

docs: explain how to use fix_code

fix: allow fix_files to read paths to files as arguments

---

.cruft.json
pdm.lock
pyproject.toml

ci: limit the markdown library version till the issue is solved

---

.cruft.json
.github/workflows/build.yml
.github/workflows/tests.yml
.github/workflows/update.yml
src/yamlfix/services.py
tests/unit/test_services.py

fix: don't erase strings that are a jinja2 variable expansion

---

src/yamlfix/entrypoints/cli.py
src/yamlfix/services.py
tests/e2e/test_cli.py
tests/unit/test_services.py

Hi @lyz-code,
as per discussion on #181 please see the attached changes. I went with a slightly different approach rather than throwing an exception, let me know what you think!

CLI --check / dry-run mode

---

pdm.lock

chore: update dependencies

---

.cruft.json
Makefile
pyproject.toml

tests: improve testing environment

---

docs/index.md
src/yamlfix/adapters.py
src/yamlfix/model.py
tests/unit/test_adapter_yaml.py

Add configuration option to specify section white lines.
Fixes #211

feat(adapters.py): Add section whitelines

---

docs/index.md
src/yamlfix/adapters.py
tests/unit/test_adapter_yaml.py

Fix whitelines parameter not being respected when higher than section_whitelines
