src/yamlfix/services.py
tests/unit/test_services.py

Correct indentation of top level lists, closes #5 
Also refactored _add_heading in favour of explicit_start attribute
ruyaml parser has the attribute explicit_start which does the same.

fix: correct indentation of top level lists (#5)

---

docs/index.md
src/yamlfix/services.py
tests/unit/test_services.py

yamllint specifies that is forbidden to use non-explictly typed truthy values other than allowed ones (by default: true and false), for example YES or off. Transform these strings to true and false.
Closes #3

feat: correct truthy strings (#3)

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml

Otherwise the update pipeline fails due to the tornadoweb issue [#2981](https://github.com/tornadoweb/tornado/issues/2981)

ci: disable safety pre-commit

---

src/yamlfix/services.py
tests/unit/test_services.py

Code like:
```yaml
---
foo: bar
```
Got indented as:
```yaml
---
foo: bar
```
Thus breaking the link. This commit fixes that behaviour and closes #70

fix: respect anchors in urls

---

Makefile
docs/requirements.txt
requirements-dev.txt
tests/e2e/test_cli.py

ci: remove the security bypass of 39462
style: use pytest.mark.secondary()
@pytest.mark.secondary started to break the linter

chore: update requirements

---

.pre-commit-config.yaml
src/yamlfix/services.py
tests/unit/test_services.py

This PR fixes issue https://github.com/lyz-code/yamlfix/issues/9.
As indicated in the issue, I checked the [ruyaml options](https://github.com/pycontribs/ruyaml/blob/725bccd8aed1cd2aec746eae2a7c910739511d94/lib/ruamel/yaml/main.py#L141-L168) to see if there was any support for multiple files but this feature is already supported in the original [PyYAML library](https://pyyaml.org/wiki/PyYAMLDocumentation) and ruyaml follows the same strategy.
So I made the following changes:
- Added support for multiple file documents by using `load_all` instead of `load` and then iterating through the results to dump them to the stream.
- Added a test case to check if multiple document files are parsed. I didn't add tests for format fixes in multiple document files since the logic for the other fixes …

feat: Allow formatting files with multiple documents

---

src/yamlfix/entrypoints/__init__.py
src/yamlfix/entrypoints/cli.py
src/yamlfix/services.py
tests/e2e/test_cli.py
tests/unit/test_services.py

Description of the changes:
- Added a custom logging formatter for the colored plus signs, instead of setting them as replacement for level names. I did this to be able to keep the level names, as they can be useful to test logging (since they are more readable than the ANSI sequences).
- Added the `--verbose` flag to the CLI and loaded the logger. Added two INFO logs to indicate that yamlfix is running and DEBUG logs for each file and fixer.
- Added a CLI test for the `--verbose` flag (checking stderr) and also a unit test for the DEBUG logs in the fixer functions (using the pytest caplog fixture).
- Marked the `files` argument as required, because if that argument is not present running `yamlfix` is a no-op.
- Removed the workaround for the `CliRunner` error in the stdin tests because I …

feat: Add logging with tests

---

src/yamlfix/services.py

A log added for testing purposes had not been removed. It didn't affect functionality, but it wasn't necessary.

Remove leftover warning log

---

docs/index.md
src/yamlfix/services.py
tests/e2e/test_cli.py
tests/unit/test_services.py

Fixes issue https://github.com/lyz-code/yamlfix/issues/115.
I added a new fixer function to add the newline at the end because I thought it was a simpler and more readable solution than changing all the code in the other fixer functions where the trailing whitespace was removed. The newlines were being removed not only in `_ruamel_yaml_fixer` (through the use of `strip()`) but also every time `splitlines()` is called:
```python
>>> from textwrap import dedent
>>> source = dedent("""\
...     ---
...     program: yaml_fix
...     """
... )
>>> source_lines = source.splitlines()
>>> print(source_lines)
['---', 'program: yaml_fix']
```
Using `splitlines()` with `keepends=True` would also be complicated since it would also keep unwanted whitespace in every line and not just at the end.
Also, …

fix: add newline at end of file

---

.github/workflows/install.yml
.github/workflows/tests.yml
docs/contributing.md
pyproject.toml
requirements-dev.txt
requirements.txt
setup.py
tests/unit/test_services.py

Fixes https://github.com/lyz-code/yamlfix/issues/120.
The behavior was caused by a bug in previous versions of ruyaml, fixed in [this commit](https://github.com/pycontribs/ruyaml/commit/1be1a708aaeffc55271d9c86ff56a59c14de4556).
I added a test to reproduce the bug reported and it failed. As expected, test passed after updating ruyaml dependency.

fix: update ruyaml version with anchor bug fix

---

src/yamlfix/services.py

This ensures that fix_files' docstring matches what fix_files does.

fix: make docstring match functionality, closes #133

---

src/yamlfix/services.py
tests/unit/test_services.py

This change ensures Ansible vaults are not inadvertantly modified by yamlfix.
* [X ] Add test cases to all the changes you introduce

fix: don't modify Ansible vaults. Closes #135.

---

setup.py

Until https://github.com/pycontribs/ruyaml/issues/58 is resolved, the issue
https://github.com/lyz-code/yamlfix/issues/120 will remain because we can't
hardcode dependencies from github in the `setup.py` because Pypi doesn't allow
them.
If you need that feature, please change the "ruyaml" line in the
`setup.py` with:
```python
"ruyaml @ git+git://github.com/pycontribs/ruyaml@0.90.0.2#egg=ruyaml", # noqa E800
```
and run `make install`.

fix: revert the ruyaml dependency

---

src/yamlfix/services.py
tests/unit/test_services.py

fix: support comments in the middle of a string

---

src/yamlfix/services.py

This change prevents yamlfix from overwriting files when their content wasn't fixed by yamlfix. This avoids unnecessary disk I/O.

feat: don't overwrite files if content is not modified. Closes #142.

---

.pre-commit-hooks.yaml

Since it seems a copy-paste mistake from [here](https://github.com/lyz-code/autoimport/blob/d776b6b1c6a76ded1dd2057345f8b7b56321fbb0/.pre-commit-hooks.yaml) or somewhere else, I fixed it to be the same as [yamllint](https://github.com/adrienverge/yamllint/blob/d0392b34ca15fb56061a4edc594ae2dd67b0cff9/.pre-commit-hooks.yaml#L11).

fix: fix types of pre-commit-hooks

---

.pre-commit-config.yaml
docs/index.md
docs/reference.md
pdm.lock
pyproject.toml
src/yamlfix/adapters.py
src/yamlfix/config.py
src/yamlfix/entrypoints/cli.py
src/yamlfix/model.py
src/yamlfix/services.py
tests/e2e/test_cli.py
tests/unit/test_adapter_yaml.py
tests/unit/test_services.py

This fixes #117 and fixes #190 
- make default values, like line_length, explicit_start and indentation configurable
- add configuration option for none-value representation
- add configuration option for quote-style representation
- add configuration option for flow-style / block-style sequences
- add an option to quote every key and value
- add an option to quote only simple values
- add an option to switch between multi-line flow-style and flow-style
-> block-style conversion if the list doesn't fit the line_length
- implement reading of configuration values from files (with maison)
- implement overriding specific values with prefixed env vars

feat: make yamlfix configurable with sane default values

---

docs/index.md
pyproject.toml
src/yamlfix/adapters.py
src/yamlfix/model.py
tests/unit/test_adapter_yaml.py
tests/unit/test_services.py

Resolves #193 -- Remove extra whitelines
* [SourceCodeFixer._fix_whitelines()](https://github.com/lyz-code/yamlfix/blob/024abb478ab0edff6986d290ea7502c7c400ee11/src/yamlfix/adapters.py#L629): Used to return the yaml following the appropriate whitelines standards
* [SourceCodeFixer._removes_extra_whitelines()](https://github.com/lyz-code/yamlfix/blob/024abb478ab0edff6986d290ea7502c7c400ee11/src/yamlfix/adapters.py#L366): Used to return a single new line character followed by the last character of a matched string
* A line that that includes only a comment can have either:
* 0 preceding whiteline
* `comments_optional_number_whitelines_from_content` whiteline(s)
For example, if `comments_optional_number_whitelines_from_content==2` these `YaML` are valid:
```
key1: value1
key2: value2
```
``` …
```

[#193]: Allowing optional number of whitelines before comments

---

docs/index.md
src/yamlfix/adapters.py
tests/unit/test_services.py

Resolves #210 -- Allow whitelines on comments that are not on the first level of indentation
`re_whitelines_with_comments = "\n\n+[\t ]{0,}[#]"`:
* `\n\n+`: Match 2+ newline (i.e. 1+ whiteline)
* `[\t ]{0,}`: Match between `0` and `unlimited` number of `tab` or `space`
* `[#]`: Match a `#`, the first character of a comment
`re_whitelines_with_no_comments = "\n\n+[\t ]{0,}[^#\n\t ]"`:
* `\n\n+`: Match 2+ newline (i.e. 1+ whiteline)
* `[\t ]{0,}`: Match between `0` and `unlimited` number of `tab` or `space`
* `[^#\n\t ]`: Match any character but `#`, `tab` or `space`

[#210]: Allow whitelines followed by indented comment

---

docs/index.md
src/yamlfix/entrypoints/cli.py
tests/e2e/test_cli.py

Ability to glob on directories
Fixes #162, Fixes #205
After checking the behaviour of `black` and `isort`, I see that they don't actually glob on no arguments, so I replicated the behaviour here.
`yamlfix .` should work now.

feat(cli.py): Add ability to glob on directories

---

src/yamlfix/entrypoints/__init__.py
src/yamlfix/entrypoints/cli.py
src/yamlfix/services.py
tests/e2e/test_cli.py

Only list changed files by default
Fixes #216
Current behaviour:
* No flag: Print summary and changed files at `INFO` level
* One flag: + print unchanged files at `15` level
* Two+ flags: + print `DEBUG` information.
Also, added short version of `--verbose` flag (`-v`) and changed it to counter, so any combination (e.g. `-v -v`, `-vv`, `-v --vebose`) should work.

feat(services.py): Change behaviour to only list changed files by default

---

src/yamlfix/adapters.py
tests/unit/test_adapter_yaml.py

The regex would check for `---\n` as the file start which would not necessarily apply if `explicit_start=False`. This change also considers `\A` as an alternative file start.
I wasn't able to find an open issue to link this change to. Please advise if any documentation is required for this change.

fix: account for explicit_start=False when handling whitelines

---

docs/editor_integration.md

Upstream repo is using 'main' as the default branch

Swap rev from master to main

---

docs/index.md
src/yamlfix/adapters.py
src/yamlfix/model.py
tests/unit/test_adapter_yaml.py

Default: `preserve_quotes: bool = False`<br>
Environment variable override:
```bash
export YAMLFIX_preserve_quotes="false"
```
Keep quotes as they are
```yaml
key: [value, 'value with spaces']
```
```yaml
key: [value, value with spaces]
```
```yaml
key: [value, 'value with spaces']
```
**Notes:**
You may NOT want to use it in combination with [quote basic values](#quote-basic-values) or [quote keys and basic values](#quote-keys-and-basic-values), because the output may not be uniform
Example: `quote_basic_values`
```yaml
key: [value, 'value with spaces']
```
```yaml
key: ["value", 'value with spaces']
```
Example: `quote_keys_and_basic_values`
```yaml
key: [value, 'value with spaces']
```
```yaml
"key": ["value", 'value with spaces']
```

Allow to preserve quotes

---

docs/index.md
src/yamlfix/entrypoints/cli.py
tests/e2e/test_cli.py

Solves part of #243
* Add `--include <glob>` and `--exclude <glob>` to the CLI to allow including and excluding specific files when passing directories via the CLI.
* This change is backwards compatible with the previous implementation.

feat: add include and exclude cli options

---

src/yamlfix/entrypoints/cli.py
tests/e2e/test_cli.py

This allows for excluding whole directories recursively, rather than just at a top level as previous. The motivation for this change was wanting to exclude a whole directory, e.g. a virtual environment `venv/**/*` or a compiled target directory with multiple subdirectories: `**/target/**/*`.

Allow wildcarding nested dirs in exclusion logic

---

src/yamlfix/entrypoints/cli.py
tests/e2e/test_cli.py

Fixed a bug that yamlfix crashes when it encounters a folder that looks like a yaml file (e.g. folder.yml or folder.yaml).
See issue #256

Bug fix: ignore folders that look like yaml files.

---

pyproject.toml
src/yamlfix/services.py
tests/unit/test_services.py

Preserves the jinja2 ansible headers `# jinja2:` like: `# jinja2:lstrip_blocks: true`
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
> Also, you can override jinja2 settings by adding a special header to template file. i.e. 
#jinja2:variable_start_string:'[%', variable_end_string:'%]', trim_blocks: False 
Useful when using `jinja2.ansible`:
```yaml
#jinja2:lstrip_blocks: True
---
global:
resolve_timeout: 1m'
route:
...
```

preserv ansible # jinja2 header

---

.github/workflows/install.yml
.github/workflows/tests.yml
mkdocs.yml
pdm.lock
pyproject.toml

fix: drop support for Python 3.7
fix: switch from pdm-pep517 to pdm-backend
chore: updte requirements

feat: support Python 3.11

---

.safety-policy.yml
pdm.lock
pyproject.toml
src/yamlfix/config.py
src/yamlfix/entrypoints/cli.py
src/yamlfix/model.py
src/yamlfix/services.py

Bugfix for https://github.com/lyz-code/yamlfix/issues/271
Opening all files at once does not seem necessary. `fix_files` already handles `str` file paths and opens them automatically.
Also, 
* `maison 2.0.0` was released today and introduces breaking changes (`maison.schema` does not exist anymore), so dependency rules are updated to be a bit more restrictive. Updated to `maison 2.0.0` will require a separate PR.
* `black` is updated to >=24.3 to fix a vulnerability issue detected by `safety`
* a `.safety-policy.yml` file is generated to ignore a `jinja2 3.1.4` vulnerability that can probably be ignored since we don't use jinja2's `from_string` function?

Fix too many open files error

---

pyproject.toml
src/yamlfix/entrypoints/cli.py
tests/e2e/test_cli.py
tests/unit/test_cli_cache.py

This PR introduces a glob caching mechanism to improve the performance of file discovery in the CLI, particularly for large directories and repeated glob operations. It also adds comprehensive tests to ensure correct cache behavior and performance gains.
* Added unit tests in `tests/unit/test_cli_cache.py` to verify correct cache key construction, separation of entries, cache clearing, and correct results for both `glob` and `rglob` operations.
* Added end-to-end tests in `tests/e2e/test_cli.py` to measure and assert performance improvements from caching, including a slow test to compare cached vs. uncached runs for exclude patterns.

Cache globbed files for speed increase
